SELECT SUBSTR(TRIM(' ' FROM GLDOC),1,8) as "Doc Voucher Invoice etc",
GLDGJ as "GL_Date_Temp",
TRIM(' ' FROM GLKCO) as "Doc Co",
TRIM(' ' FROM GLDCT) as "Doc Type",
GLJELN as "Journal Entry Line No",
TRIM(' ' FROM GLEXTL) as "Line Extension Code",
GLAA/100 as "Amt",
GLU/100 as "Units",
TRIM(' ' FROM GLUM) as "Unit of Measure",
TRIM(' ' FROM GLPO) as "Purchase Order",
TRIM(' ' FROM GLPSFX) as "Purchase Order Suffix",
TRIM(' ' FROM GLDCTO) as "Order Type",
TRIM(' ' FROM GLPDCT) as "Doc Type Purchase Order",
SUBSTR(TRIM(' ' FROM GLAN8),1,8) as "Add No",
TRIM(' ' FROM GLEXA) as "Name Alpha Explanation",
TRIM(' ' FROM GLCN) as "Pmt No",
GLDKJ as "Date_Check_Julian_Temp",
GLDKC as "Date_Check_Cleared_Temp",
GLLNID/1000 as "Line No",
TRIM(' ' FROM GLVINV) as "Supplier Invoice No",
GLIVD as "Invoice_Date_Temp",
TRIM(' ' FROM GLPOST) as "G L Posted Code",
SUBSTR(TRIM(' ' FROM GLICU),1,8) as "Batch No",
TRIM(' ' FROM GLICUT) as "Batch Type",
GLDICJ as "Date_Batch_Julian_Temp",
GLDSYJ as "Date_Batch_System_Date_Temp",
GLTICU as "Batch Time",
TRIM(' ' FROM GLCO) as "Co",
TRIM(' ' FROM GLANI) as "Acct No Input Mode Unk",
TRIM(' ' FROM GLAM) as "Acct Mode G L",
TRIM(' ' FROM GLAID) as "Acct ID",
TRIM(' ' FROM GLMCU) as "Business Unit",
TRIM(' ' FROM GLOBJ) as "Object Acct",
TRIM(' ' FROM GLSUB) as "Subsidiary",
TRIM(' ' FROM GLSBL) as "Subledger G L",
TRIM(' ' FROM GLSBLT) as "Subledger Type",
TRIM(' ' FROM GLLT) as "Ledger Types",
GLPN as "Period No GL",
GLCTRY as "Century",
GLFY as "Fiscal Year",
TRIM(' ' FROM GLFQ) as "Fiscal Quarter Obsolete",
TRIM(' ' FROM GLCRCD) as "Currency Code From",
TRIM(' ' FROM GLGLC) as "G L Offset",
TRIM(' ' FROM GLRE) as "Reverse or Void R V",
TRIM(' ' FROM GLEXR) as "Name Remark Explanation",
TRIM(' ' FROM GLR1) as "Reference1 JE Vouch Inv",
TRIM(' ' FROM GLR2) as "Reference 2",
TRIM(' ' FROM GLR3) as "Reference 3 Acct Rec",
TRIM(' ' FROM GLSFX) as "Doc Pay Item",
GLODOC as "Doc Original",
TRIM(' ' FROM GLASID) as "Serial No",
TRIM(' ' FROM GLBRE) as "Batch Rear End Posted Code",
TRIM(' ' FROM GLRCND) as "Reconciled Code",
TRIM(' ' FROM GLSUMM) as "Summarized Code",
TRIM(' ' FROM GLPRGE) as "Purge Code",
TRIM(' ' FROM GLALT8) as "Billing Control",
TRIM(' ' FROM GLALT9) as "Currency Update",
TRIM(' ' FROM GLALTZ) as "GL Post Code Acct DrBal",
TRIM(' ' FROM GLDLNA) as "Delete Not Allowed",
TRIM(' ' FROM GLBC) as "Bill Code",
TRIM(' ' FROM GLWR01) as "Categories Work Order 01",
GLWY as "Fiscal Year Weekly",
GLWN as "Fiscal Period Weekly",
TRIM(' ' FROM GLJBCD) as "Job Type Craft Code",
TRIM(' ' FROM GLJBST) as "Job Step",
TRIM(' ' FROM GLHMCU) as "Business Unit Home",
GLDOI as "DOI Sub",
TRIM(' ' FROM GLALID) as "Outsider Lease or Well ID",
TRIM(' ' FROM GLALTY) as "ID Type",
GLDSVJ as "Date_Service_Tax_Temp",
TRIM(' ' FROM GLTORG) as "Transaction Originator",
SUBSTR(TRIM(' ' FROM GLPYID),1,15) as "Pmt ID Internal",
TRIM(' ' FROM GLUSER) as "User ID",
TRIM(' ' FROM GLPID) as "Program ID",
TRIM(' ' FROM GLJOBN) as "Work Station ID",
GLUPMJ as "Date_Updated_Temp",
GLUPMT as "Time Last Updated"       
FROM %v_SCHEMA1%.F0911 A
WHERE(A.GLCO IN (%v_CompanyCode1%, %v_CompanyCode2%, %v_CompanyCode3%, %v_CompanyCode4%, %v_CompanyCode5%, %v_CompanyCode6%, %v_CompanyCode7%, %v_CompanyCode8%, %v_CompanyCode9%, %v_CompanyCode10%, %v_CompanyCode11%, %v_CompanyCode12%, %v_CompanyCode13%, %v_CompanyCode14%, %v_CompanyCode15%))
AND (A.GLDGJ BETWEEN %v_BeginAuditPeriod% AND %v_EndAuditPeriod%)
AND (A.GLCO <> ' ')
AND (A.GLDCT = %v_GLDocumentType1% OR A.GLDCT = %v_GLDocumentType2% or A.GLDCT = %v_GLDocumentType3% or A.GLDCT = %v_GLDocumentType4% or A.GLDCT = %v_GLDocumentType5%)