COM *********************************************************
COM *** Import General Ledger Table
COM *********************************************************

SELECT LTRIM(STR(GLDOC,8)) as 'Doc Voucher Invoice etc',
GLDGJ as 'GL_Date_Temp',
LTRIM(GLKCO) as 'Doc Co',
LTRIM(GLDCT) as 'Doc Type',
GLJELN as 'Journal Entry Line No',
LTRIM(GLEXTL) as 'Line Extension Code',
GLAA/100 as 'Amt',
GLU/100 as 'Units',
LTRIM(GLUM) as 'Unit of Measure',
LTRIM(GLPO) as 'Purchase Order',
LTRIM(GLPSFX) as 'Purchase Order Suffix',
LTRIM(GLDCTO) as 'Order Type',
LTRIM(GLPDCT) as 'Doc Type Purchase Order',
LTRIM(STR(GLAN8,8)) as 'Add No',
LTRIM(GLEXA) as 'Name Alpha Explanation',
LTRIM(GLCN) as 'Pmt No',
GLDKJ as 'Date_Check_Julian_Temp',
GLDKC as 'Date_Check_Cleared_Temp',
GLLNID/1000 as 'Line No',
LTRIM(GLVINV) as 'Supplier Invoice No',
GLIVD as 'Invoice_Date_Temp',
LTRIM(GLPOST) as 'G L Posted Code',
LTRIM(STR(GLICU,8)) as 'Batch No',
LTRIM(GLICUT) as 'Batch Type',
GLDICJ as 'Date_Batch_Julian_Temp',
GLDSYJ as 'Date_Batch_System_Date_Temp',
GLTICU as 'Batch Time',
LTRIM(GLCO) as 'Co',
LTRIM(GLANI) as 'Acct No Input Mode Unk',
LTRIM(GLAM) as 'Acct Mode G L',
LTRIM(GLAID) as 'Acct ID',
LTRIM(GLMCU) as 'Business Unit',
LTRIM(GLOBJ) as 'Object Acct',
LTRIM(GLSUB) as 'Subsidiary',
LTRIM(GLSBL) as 'Subledger G L',
LTRIM(GLSBLT) as 'Subledger Type',
LTRIM(GLLT) as 'Ledger Types',
GLPN as 'Period No GL',
GLCTRY as 'Century',
GLFY as 'Fiscal Year',
LTRIM(GLFQ) as 'Fiscal Quarter Obsolete',
LTRIM(GLCRCD) as 'Currency Code From',
LTRIM(GLGLC) as 'G L Offset',
LTRIM(GLRE) as 'Reverse or Void R V',
LTRIM(GLEXR) as 'Name Remark Explanation',
LTRIM(GLR1) as 'Reference1 JE Vouch Inv',
LTRIM(GLR2) as 'Reference 2',
LTRIM(GLR3) as 'Reference 3 Acct Rec',
LTRIM(GLSFX) as 'Doc Pay Item',
GLODOC as 'Doc Original',
LTRIM(GLASID) as 'Serial No',
LTRIM(GLBRE) as 'Batch Rear End Posted Code',
LTRIM(GLRCND) as 'Reconciled Code',
LTRIM(GLSUMM) as 'Summarized Code',
LTRIM(GLPRGE) as 'Purge Code',
LTRIM(GLALT8) as 'Billing Control',
LTRIM(GLALT9) as 'Currency Update',
LTRIM(GLALTZ) as 'GL Post Code Acct DrBal',
LTRIM(GLDLNA) as 'Delete Not Allowed',
LTRIM(GLBC) as 'Bill Code',
LTRIM(GLWR01) as 'Categories Work Order 01',
GLWY as 'Fiscal Year Weekly',
GLWN as 'Fiscal Period Weekly',
LTRIM(GLJBCD) as 'Job Type Craft Code',
LTRIM(GLJBST) as 'Job Step',
LTRIM(GLHMCU) as 'Business Unit Home',
GLDOI as 'DOI Sub',
LTRIM(GLALID) as 'Outsider Lease or Well ID',
LTRIM(GLALTY) as 'ID Type',
GLDSVJ as 'Date_Service_Tax_Temp',
LTRIM(GLTORG) as 'Transaction Originator',
LTRIM(STR(GLPYID,15)) as 'Pmt ID Internal',
LTRIM(GLUSER) as 'User ID',
LTRIM(GLPID) as 'Program ID',
LTRIM(GLJOBN) as 'Work Station ID',
GLUPMJ as 'Date_Updated_Temp',
GLUPMT as 'Time Last Updated'       
FROM %v_SCHEMA1%.F0911 A
WHERE(A.GLCO IN (%v_CompanyCode1%, %v_CompanyCode2%, %v_CompanyCode3%, %v_CompanyCode4%, %v_CompanyCode5%, %v_CompanyCode6%, %v_CompanyCode7%, %v_CompanyCode8%, %v_CompanyCode9%, %v_CompanyCode10%, %v_CompanyCode11%, %v_CompanyCode12%, %v_CompanyCode13%, %v_CompanyCode14%, %v_CompanyCode15%))  
AND (A.GLDGJ BETWEEN %v_BeginAuditPeriod% AND %v_EndAuditPeriod%)
AND (A.GLCO <> '')
AND (A.GLDCT = %v_GLDocumentType1% OR A.GLDCT = %v_GLDocumentType2% or A.GLDCT = %v_GLDocumentType3% or A.GLDCT = %v_GLDocumentType4% or A.GLDCT = %v_GLDocumentType5%)
